#lanciare con   sudo ansible-playbook --extra-vars "ip_var=localhost" readvar.yml
---
- hosts: localhost
  become: yes
  tasks:
  - name: Install packages
    apt:
      name:
      - nmap
      state: latest
      cache_valid_time: 3600
  - name: Scan host using nmap
    shell: nmap -A T4 "{{ ip_var }}"
    register: out

  - debug: var=out.stdout_lines
